"use client";

import Head from "next/head";
// import type { Metadata } from "next";
import "./globals.css";
import { RecoilRoot } from "recoil"; // Імпортуємо RecoilRoot

// export const metadata: Metadata = {
//   title: "theLAW",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <Head>
            <title>theLAW</title>
            <meta name="description" content="Юридичні консультації" />
          </Head>
          {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
